CREATE DATABASE TIENDA
GO

USE TIENDA

CREATE TABLE USERS (
	id INT IDENTITY PRIMARY KEY,
	first_name NVARCHAR(100) NOT NULL,
	last_name NVARCHAR(100) NOT NULL,
	birthdate DATE NULL
);

CREATE TABLE ORDERS (
	id INT IDENTITY PRIMARY KEY,
	total DECIMAL NOT NULL,
	date DATE NULL DEFAULT GETDATE(),
	id_user INT NOT NULL
	FOREIGN KEY (id_user) REFERENCES USERS (id)
);

CREATE TABLE ORDER_DETAILS (
	id INT IDENTITY PRIMARY KEY,
	total_productos INT NOT NULL,
	descuento BIT NOT NULL,
	id_order INT NOT NULL
	FOREIGN KEY (id_order) REFERENCES ORDERS(id)
);